version: "3.2"

services:
  documents-api:
    image: documents-api
    build:
      context: DocumentsApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  documents-api-test:
    image: documents-api-test
    build:
      context: .
      dockerfile: DocumentsApi.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=documents_api_test
      - S3_API_ENDPOINT=http://s3-mock:80
    env_file:
      - .env.example
    links:
      - test-database
      - s3-mock

  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env

  s3-mock:
    image: andrewgaul/s3proxy
    ports:
      - 5555:80
    environment:
      - S3PROXY_AUTHORIZATION=none
      - S3PROXY_CORS_ALLOW_ALL=true
      - LOG_LEVEL=debug
